logging:
  level:
    root: INFO
    
server:
  port: 15000
  servlet:
    context-path: /${spring.application.name}
    
spring:
  application:
    name: manager
  thymeleaf:
    suffix: .html
    cache: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false

  datasource:
    url: jdbc:mysql://localhost:3306/machine_manager_db?useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=America/Fortaleza&createDatabaseIfNotExist=true
    username: root
    password: senha.123.ph